config/routes.rb
Rails.application.routes.draw do
  root 'blogs#top'
  resources :feeds
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :contacts
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :favorites, only: [:create, :destroy]
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content, length:{ in: 1..140}
  validates :image, presence: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user, optional: true
  mount_uploader :image, ImageUploader
  #そのユーザーが既にツイートにいいねしているかどうか
  def favorite_user(user_id)
    favorites.find_by(user_id: user_id)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def top
  end
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.order("created_at DESC")
    @user = User.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    @username = current_user
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @username = current_user
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    respond_to do |format|
      if @blog.save
        ContactMailer.contact_mail(@blog).deliver
        format.html { redirect_to @blog, notice: 'Your Post was successful！' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :image, :image_cache)
    end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, url: confirm_blogs_path) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div align="center">
    <div class="field">
      <%= form.label :image %>
      <%= image_tag(@blog.image.url) if @blog.image.url %>
      <%= form.file_field :image, id: :feed_image %>

    </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :blog_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
    </div>
<% end %>

app/views/blogs/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <title>DIVE INTO CODE</title>

    <!-- Custom fonts for this template -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/blogs/confirm.html.erb
<div id="content">
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>img:<br><%= image_tag(@blog.image) %></p>
  <p>本文:<%= @blog.content %></p>
  <button type="submit" class="btn btn-primary">登録する</button>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <button type="submit" class="btn btn-default">戻る</button>
<% end %>
</div>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<tbody>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    <h1 class="page-header">みんなの投稿</h1>
      <% @blogs.each do |blog| %>
      <ul class="list-group">
        <li class="list-group-item"><%= link_to "#{blog.user.name}", blog %></li>
        <li class="list-group-item"><%= image_tag(blog.image, :class => "image_content center-block")%></li>
        <li class="list-group-item"><%= blog.content %></li>
        <% if logged_in? %>
        <% if blog.user_id == current_user.id %>
        <li class="list-group-item">
          <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-default ' %>
          <%= link_to 'Delete', blog, class: 'btn btn-danger ', method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
        <% end %>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
</div>
</tbody>

app/views/blogs/new.html.erb
<h1>新しく投稿します</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<p>
<strong>Image:</strong>
<p><%= image_tag @blog.image %></p>
<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> | <%= link_to 'Back', blogs_path %>

app/views/blogs/top.html.erb
<div class="bk_img">
  <div class="topcontents">
    <h1>InstagramClone</h1>
  </div>
</div>